name: Deploy

on: workflow_dispatch

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p ~/.ssh
          '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
          ~/.composer/vendor/bin/envoy run deploy
