name: Deploy

on: workflow_dispatch

jobs:
  Test:
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/usspnaym/be/env:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy
        run: ~/.composer/vendor/bin/envoy run deploy
