name: Deploy

on: workflow_dispatch

jobs:
  Test:
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/usspnaym/be/env:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      #- uses: webfactory/ssh-agent@v0.5.3
      #  with:
      #    ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy
        run: |
          composer global require "laravel/envoy=~1.0"
          mkdir -p ~/.ssh
          ssh-keyscan t22.tfcis.org >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts
          # echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile /dev/null\n\n" > ~/.ssh/config
          eval `ssh-agent -s`
          echo "$PRIV" | ssh-add -
          ~/.composer/vendor/bin/envoy run deploy

        env:
          PRIV: ${{ secrets.SSH_PRIVATE_KEY }}
